import { Category, ColorMetaGrouped } from "../types/theme";

export const colorCategoryMap: ColorMetaGrouped = {
  // --- Base ---
  foreground: {
    category: "Base",
    subcategory: "Core",
    displayName: "Foreground",
    description: "Default UI text color",
  },
  disabledForeground: {
    category: "Base",
    subcategory: "Core",
    displayName: "Disabled Text",
    description: "Dimmed UI text color",
  },
  descriptionForeground: {
    category: "Base",
    subcategory: "Core",
    displayName: "Description Text",
    description: "Supplementary text color",
  },
  errorForeground: {
    category: "Base",
    subcategory: "Core",
    displayName: "Error Text",
    description: "Error messages text color",
  },
  "icon.foreground": {
    category: "Base",
    subcategory: "Core",
    displayName: "Icon Color",
    description: "Default icon color",
  },
  focusBorder: {
    category: "Base",
    subcategory: "Borders",
    displayName: "Focus Border",
    description: "Boundaries on focused elements",
  },
  contrastBorder: {
    category: "Base",
    subcategory: "Borders",
    displayName: "Contrast Border",
    description: "High contrast element border",
  },
  contrastActiveBorder: {
    category: "Base",
    subcategory: "Borders",
    displayName: "Active Contrast Border",
    description: "Active item high contrast",
  },
  "widget.border": {
    category: "Base",
    subcategory: "Widgets",
    displayName: "Widget Border",
    description: "Border around widgets",
  },
  "widget.shadow": {
    category: "Base",
    subcategory: "Widgets",
    displayName: "Widget Shadow",
    description: "Widget drop shadow",
  },
  "selection.background": {
    category: "Base",
    subcategory: "Selection",
    displayName: "Global Selection",
    description: "Workbench selection background",
  },
  "scrollbar.shadow": {
    category: "Base",
    subcategory: "Scrollbar",
    displayName: "Scrollbar Shadow",
    description: "Shadow behind scrollbar",
  },
  "scrollbarSlider.background": {
    category: "Base",
    subcategory: "Scrollbar",
    displayName: "Scrollbar Thumb",
    description: "Thumb background",
  },
  "scrollbarSlider.hoverBackground": {
    category: "Base",
    subcategory: "Scrollbar",
    displayName: "Scrollbar Hover",
    description: "Thumb hover background",
  },
  "scrollbarSlider.activeBackground": {
    category: "Base",
    subcategory: "Scrollbar",
    displayName: "Scrollbar Active",
    description: "Thumb active background",
  },
  "sash.hoverBorder": {
    category: "Base",
    subcategory: "Sash",
    displayName: "Sash Hover Border",
    description: "Resizer hover border",
  },

  // --- Editor ---
  "editor.background": {
    category: "Editor",
    subcategory: "Core",
    displayName: "Editor Background",
    description: "Editor background color",
  },
  "editor.foreground": {
    category: "Editor",
    subcategory: "Core",
    displayName: "Editor Text",
    description: "Default editor text color",
  },
  "editorLineNumber.foreground": {
    category: "Editor",
    subcategory: "Core",
    displayName: "Line Numbers",
    description: "Color of line numbers",
  },
  "editorLineNumber.activeForeground": {
    category: "Editor",
    subcategory: "Core",
    displayName: "Active Line Number",
    description: "Current line number color",
  },
  "editorCursor.foreground": {
    category: "Editor",
    subcategory: "Cursor",
    displayName: "Cursor Color",
    description: "Editor cursor color",
  },
  "editor.selectionBackground": {
    category: "Editor",
    subcategory: "Selection",
    displayName: "Selection Background",
    description: "Text selection background",
  },
  "editor.selectionHighlightBackground": {
    category: "Editor",
    subcategory: "Selection",
    displayName: "Selection Highlight",
    description: "Inactive selection highlight",
  },
  "editor.findMatchBackground": {
    category: "Editor",
    subcategory: "Find/Replace",
    displayName: "Find Match",
    description: "Current search match highlight",
  },
  "editor.findMatchHighlightBackground": {
    category: "Editor",
    subcategory: "Find/Replace",
    displayName: "Find Highlights",
    description: "Other search matches highlight",
  },
  "editor.findRangeHighlightBackground": {
    category: "Editor",
    subcategory: "Find/Replace",
    displayName: "Find Range",
    description: "Search limit background",
  },
  "editorBracketMatch.background": {
    category: "Editor",
    subcategory: "Brackets",
    displayName: "Bracket Background",
    description: "Bracket match background",
  },
  "editorBracketMatch.border": {
    category: "Editor",
    subcategory: "Brackets",
    displayName: "Bracket Border",
    description: "Bracket match border",
  },
  "editorIndentGuide.background": {
    category: "Editor",
    subcategory: "Guides",
    displayName: "Indent Guide",
    description: "Inactive indent guides",
  },
  "editorIndentGuide.activeBackground": {
    category: "Editor",
    subcategory: "Guides",
    displayName: "Active Indent Guide",
    description: "Active indent guide color",
  },
  "editor.ruler.foreground": {
    category: "Editor",
    subcategory: "Guides",
    displayName: "Ruler Line",
    description: "Column ruler color",
  },
  "editorOverviewRuler.border": {
    category: "Editor",
    subcategory: "Overview",
    displayName: "Overview Border",
    description: "Overview ruler border",
  },
  "editorOverviewRuler.findMatchForeground": {
    category: "Editor",
    subcategory: "Overview",
    displayName: "Overview Find Highlight",
    description: "Find match in overview",
  },
  "editorWidget.background": {
    category: "Editor",
    subcategory: "Widgets",
    displayName: "Widget Background",
    description: "Inline widget background",
  },
  "editorWidget.border": {
    category: "Editor",
    subcategory: "Widgets",
    displayName: "Widget Border",
    description: "Inline widget border",
  },
  "editorSuggestWidget.background": {
    category: "Editor",
    subcategory: "Widgets",
    displayName: "Suggest Widget BG",
    description: "Completion popup background",
  },
  "editorSuggestWidget.foreground": {
    category: "Editor",
    subcategory: "Widgets",
    displayName: "Suggest Widget Text",
    description: "Completion popup text",
  },
  "editorSuggestWidget.selectedBackground": {
    category: "Editor",
    subcategory: "Widgets",
    displayName: "Suggest Highlight",
    description: "Selected completion background",
  },
  "editorHoverWidget.background": {
    category: "Editor",
    subcategory: "Widgets",
    displayName: "Hover Tooltip BG",
    description: "Hover tooltip background",
  },
  "editorHoverWidget.border": {
    category: "Editor",
    subcategory: "Widgets",
    displayName: "Hover Tooltip Border",
    description: "Tooltip border color",
  },
  "editorGutter.background": {
    category: "Editor",
    subcategory: "Diff",
    displayName: "Gutter Background",
    description: "Gutter background color",
  },
  "editorGutter.addedBackground": {
    category: "Editor",
    subcategory: "Diff",
    displayName: "Gutter Added",
    description: "Added line marker background",
  },
  "editorGutter.deletedBackground": {
    category: "Editor",
    subcategory: "Diff",
    displayName: "Gutter Deleted",
    description: "Deleted line marker background",
  },
  "editorGutter.modifiedBackground": {
    category: "Editor",
    subcategory: "Diff",
    displayName: "Gutter Modified",
    description: "Modified line marker background",
  },
  "diffEditor.insertedTextBackground": {
    category: "Editor",
    subcategory: "Diff",
    displayName: "Inserted Text BG",
    description: "Inserted diff background",
  },
  "diffEditor.removedTextBackground": {
    category: "Editor",
    subcategory: "Diff",
    displayName: "Removed Text BG",
    description: "Removed diff background",
  },
  "diffEditor.border": {
    category: "Editor",
    subcategory: "Diff",
    displayName: "Diff Editor Border",
    description: "Border around diff editor",
  },

  // --- Workbench ---
  "tab.activeBackground": {
    category: "Workbench",
    subcategory: "Tabs",
    displayName: "Active Tab BG",
    description: "Background of active tab",
  },
  "tab.activeForeground": {
    category: "Workbench",
    subcategory: "Tabs",
    displayName: "Active Tab Text",
    description: "Text of active tab",
  },
  "tab.inactiveBackground": {
    category: "Workbench",
    subcategory: "Tabs",
    displayName: "Inactive Tab BG",
    description: "Background of inactive tabs",
  },
  "tab.inactiveForeground": {
    category: "Workbench",
    subcategory: "Tabs",
    displayName: "Inactive Tab Text",
    description: "Text of inactive tabs",
  },
  "tab.border": {
    category: "Workbench",
    subcategory: "Tabs",
    displayName: "Tab Border",
    description: "Border between tabs",
  },
  "tab.hoverBackground": {
    category: "Workbench",
    subcategory: "Tabs",
    displayName: "Tab Hover BG",
    description: "Background on tab hover",
  },
  "tab.hoverForeground": {
    category: "Workbench",
    subcategory: "Tabs",
    displayName: "Tab Hover Text",
    description: "Text on tab hover",
  },
  "tab.activeModifiedBorder": {
    category: "Workbench",
    subcategory: "Tabs",
    displayName: "Active Modified Border",
    description: "Modification indicator on active tab",
  },
  "tab.inactiveModifiedBorder": {
    category: "Workbench",
    subcategory: "Tabs",
    displayName: "Inactive Modified Border",
    description: "Modification indicator on inactive tab",
  },
  "sideBar.background": {
    category: "Workbench",
    subcategory: "Sidebar",
    displayName: "Sidebar Background",
    description: "Background of sidebar",
  },
  "sideBar.foreground": {
    category: "Workbench",
    subcategory: "Sidebar",
    displayName: "Sidebar Text",
    description: "Text of sidebar items",
  },
  "sideBar.border": {
    category: "Workbench",
    subcategory: "Sidebar",
    displayName: "Sidebar Border",
    description: "Border around sidebar",
  },
  "sideBarSectionHeader.background": {
    category: "Workbench",
    subcategory: "Sidebar",
    displayName: "Sidebar Header BG",
    description: "Section header background",
  },
  "sideBarSectionHeader.foreground": {
    category: "Workbench",
    subcategory: "Sidebar",
    displayName: "Sidebar Header Text",
    description: "Section header text",
  },
  "sideBarTitle.foreground": {
    category: "Workbench",
    subcategory: "Sidebar",
    displayName: "Sidebar Title",
    description: "Sidebar title text color",
  },
  "activityBar.background": {
    category: "Workbench",
    subcategory: "Activity Bar",
    displayName: "Activity Bar BG",
    description: "Background of activity bar",
  },
  "activityBar.foreground": {
    category: "Workbench",
    subcategory: "Activity Bar",
    displayName: "Activity Text",
    description: "Text in activity bar",
  },
  "activityBar.border": {
    category: "Workbench",
    subcategory: "Activity Bar",
    displayName: "Activity Bar Border",
    description: "Border of activity bar",
  },
  "activityBarBadge.background": {
    category: "Workbench",
    subcategory: "Activity Bar",
    displayName: "Badge Background",
    description: "Badge background color",
  },
  "activityBarBadge.foreground": {
    category: "Workbench",
    subcategory: "Activity Bar",
    displayName: "Badge Text",
    description: "Badge text color",
  },
  "panel.background": {
    category: "Workbench",
    subcategory: "Panel",
    displayName: "Panel Background",
    description: "Background of panel",
  },
  "panel.border": {
    category: "Workbench",
    subcategory: "Panel",
    displayName: "Panel Border",
    description: "Panel border color",
  },
  "panelTitle.activeForeground": {
    category: "Workbench",
    subcategory: "Panel",
    displayName: "Active Panel Title",
    description: "Title text of active panel",
  },
  "panelTitle.inactiveForeground": {
    category: "Workbench",
    subcategory: "Panel",
    displayName: "Inactive Panel Title",
    description: "Title text of inactive panel",
  },
  "statusBar.background": {
    category: "Workbench",
    subcategory: "Status Bar",
    displayName: "Status Bar BG",
    description: "Background of status bar",
  },
  "statusBar.foreground": {
    category: "Workbench",
    subcategory: "Status Bar",
    displayName: "Status Bar Text",
    description: "Text color in status bar",
  },
  "statusBar.border": {
    category: "Workbench",
    subcategory: "Status Bar",
    displayName: "Status Bar Border",
    description: "Top border of status bar",
  },
  "statusBar.debuggingBackground": {
    category: "Workbench",
    subcategory: "Status Bar",
    displayName: "Debugging BG",
    description: "Status bar during debugging",
  },
  "statusBar.debuggingForeground": {
    category: "Workbench",
    subcategory: "Status Bar",
    displayName: "Debugging Text",
    description: "Text during debugging",
  },
  "statusBar.debuggingBorder": {
    category: "Workbench",
    subcategory: "Status Bar",
    displayName: "Debugging Border",
    description: "Border during debugging",
  },
  "titleBar.activeBackground": {
    category: "Workbench",
    subcategory: "Title Bar",
    displayName: "Title Bar BG",
    description: "Active window title bar background",
  },
  "titleBar.activeForeground": {
    category: "Workbench",
    subcategory: "Title Bar",
    displayName: "Title Bar Text",
    description: "Active window title bar text",
  },
  "titleBar.inactiveBackground": {
    category: "Workbench",
    subcategory: "Title Bar",
    displayName: "Title Bar Inactive BG",
    description: "Inactive window title bar background",
  },
  "titleBar.inactiveForeground": {
    category: "Workbench",
    subcategory: "Title Bar",
    displayName: "Title Bar Inactive Text",
    description: "Inactive window title bar text",
  },
  "titleBar.border": {
    category: "Workbench",
    subcategory: "Title Bar",
    displayName: "Title Bar Border",
    description: "Border of title bar",
  },

  // --- Tokens (Syntax colors) ---
  //   comment: {
  //     category: "Tokens",
  //     subcategory: "Syntax",
  //     displayName: "Comment",
  //     description: "Color for comments",
  //   },
  //   string: {
  //     category: "Tokens",
  //     subcategory: "Syntax",
  //     displayName: "String",
  //     description: "Color for string literals",
  //   },
  //   keyword: {
  //     category: "Tokens",
  //     subcategory: "Syntax",
  //     displayName: "Keyword",
  //     description: "Color for keywords",
  //   },
  //   number: {
  //     category: "Tokens",
  //     subcategory: "Syntax",
  //     displayName: "Number",
  //     description: "Color for numeric literals",
  //   },
  //   boolean: {
  //     category: "Tokens",
  //     subcategory: "Syntax",
  //     displayName: "Boolean",
  //     description: "Color for booleans",
  //   },
  //   variable: {
  //     category: "Tokens",
  //     subcategory: "Syntax",
  //     displayName: "Variable",
  //     description: "Color for variables",
  //   },
  //   function: {
  //     category: "Tokens",
  //     subcategory: "Syntax",
  //     displayName: "Function",
  //     description: "Color for functions",
  //   },
  //   type: {
  //     category: "Tokens",
  //     subcategory: "Syntax",
  //     displayName: "Type",
  //     description: "Color for type names",
  //   },
  //   class: {
  //     category: "Tokens",
  //     subcategory: "Syntax",
  //     displayName: "Class",
  //     description: "Color for class names",
  //   },
  //   constant: {
  //     category: "Tokens",
  //     subcategory: "Syntax",
  //     displayName: "Constant",
  //     description: "Color for constants",
  //   },
  //   "keyword.operator": {
  //     category: "Tokens",
  //     subcategory: "Syntax",
  //     displayName: "Operator",
  //     description: "Color for operators",
  //   },
  //   punctuation: {
  //     category: "Tokens",
  //     subcategory: "Syntax",
  //     displayName: "Punctuation",
  //     description: "Color for punctuation",
  //   },

  // --- Terminal ---
  "terminal.background": {
    category: "Terminal",
    subcategory: "Core",
    displayName: "Terminal Background",
    description: "Terminal background color",
  },
  "terminal.foreground": {
    category: "Terminal",
    subcategory: "Core",
    displayName: "Terminal Text",
    description: "Terminal text color",
  },
  "terminalCursor.foreground": {
    category: "Terminal",
    subcategory: "Core",
    displayName: "Terminal Cursor",
    description: "Color of terminal cursor",
  },
  "terminal.ansiBlack": {
    category: "Terminal",
    subcategory: "ANSI Colors",
    displayName: "ANSI Black",
    description: "ANSI black color",
  },
  "terminal.ansiRed": {
    category: "Terminal",
    subcategory: "ANSI Colors",
    displayName: "ANSI Red",
    description: "ANSI red color",
  },
  "terminal.ansiGreen": {
    category: "Terminal",
    subcategory: "ANSI Colors",
    displayName: "ANSI Green",
    description: "ANSI green color",
  },
  "terminal.ansiYellow": {
    category: "Terminal",
    subcategory: "ANSI Colors",
    displayName: "ANSI Yellow",
    description: "ANSI yellow color",
  },
  "terminal.ansiBlue": {
    category: "Terminal",
    subcategory: "ANSI Colors",
    displayName: "ANSI Blue",
    description: "ANSI blue color",
  },
  "terminal.ansiMagenta": {
    category: "Terminal",
    subcategory: "ANSI Colors",
    displayName: "ANSI Magenta",
    description: "ANSI magenta color",
  },
  "terminal.ansiCyan": {
    category: "Terminal",
    subcategory: "ANSI Colors",
    displayName: "ANSI Cyan",
    description: "ANSI cyan color",
  },
  "terminal.ansiWhite": {
    category: "Terminal",
    subcategory: "ANSI Colors",
    displayName: "ANSI White",
    description: "ANSI white color",
  },
  "terminal.ansiBrightBlack": {
    category: "Terminal",
    subcategory: "ANSI Colors",
    displayName: "Bright ANSI Black",
    description: "Bright ANSI black",
  },
  "terminal.ansiBrightRed": {
    category: "Terminal",
    subcategory: "ANSI Colors",
    displayName: "Bright ANSI Red",
    description: "Bright ANSI red",
  },
  "terminal.ansiBrightGreen": {
    category: "Terminal",
    subcategory: "ANSI Colors",
    displayName: "Bright ANSI Green",
    description: "Bright ANSI green",
  },
  "terminal.ansiBrightYellow": {
    category: "Terminal",
    subcategory: "ANSI Colors",
    displayName: "Bright ANSI Yellow",
    description: "Bright ANSI yellow",
  },
  "terminal.ansiBrightBlue": {
    category: "Terminal",
    subcategory: "ANSI Colors",
    displayName: "Bright ANSI Blue",
    description: "Bright ANSI blue",
  },
  "terminal.ansiBrightMagenta": {
    category: "Terminal",
    subcategory: "ANSI Colors",
    displayName: "Bright ANSI Magenta",
    description: "Bright ANSI magenta",
  },
  "terminal.ansiBrightCyan": {
    category: "Terminal",
    subcategory: "ANSI Colors",
    displayName: "Bright ANSI Cyan",
    description: "Bright ANSI cyan",
  },
  "terminal.ansiBrightWhite": {
    category: "Terminal",
    subcategory: "ANSI Colors",
    displayName: "Bright ANSI White",
    description: "Bright ANSI white",
  },

  // --- UI & Layout ---
  "button.background": {
    category: "UI & Layout",
    subcategory: "Controls",
    displayName: "Button Background",
    description: "Background of buttons",
  },
  "button.foreground": {
    category: "UI & Layout",
    subcategory: "Controls",
    displayName: "Button Text",
    description: "Text on buttons",
  },
  "button.hoverBackground": {
    category: "UI & Layout",
    subcategory: "Controls",
    displayName: "Button Hover BG",
    description: "Button background on hover",
  },
  "dropdown.background": {
    category: "UI & Layout",
    subcategory: "Controls",
    displayName: "Dropdown Background",
    description: "Dropdowns background",
  },
  "dropdown.border": {
    category: "UI & Layout",
    subcategory: "Controls",
    displayName: "Dropdown Border",
    description: "Border around dropdowns",
  },
  "dropdown.foreground": {
    category: "UI & Layout",
    subcategory: "Controls",
    displayName: "Dropdown Text",
    description: "Dropdown text color",
  },
  "input.background": {
    category: "UI & Layout",
    subcategory: "Controls",
    displayName: "Input Background",
    description: "Background of input fields",
  },
  "input.border": {
    category: "UI & Layout",
    subcategory: "Controls",
    displayName: "Input Border",
    description: "Border of input fields",
  },
  "input.foreground": {
    category: "UI & Layout",
    subcategory: "Controls",
    displayName: "Input Text",
    description: "Text in input fields",
  },
  "input.placeholderForeground": {
    category: "UI & Layout",
    subcategory: "Controls",
    displayName: "Placeholder Text",
    description: "Placeholder input text color",
  },
  "inputOption.activeBorder": {
    category: "UI & Layout",
    subcategory: "Controls",
    displayName: "Option Active Border",
    description: "Active option border",
  },
  "inputValidation.errorBackground": {
    category: "UI & Layout",
    subcategory: "Controls",
    displayName: "Error BG",
    description: "Input error background",
  },
  "inputValidation.errorBorder": {
    category: "UI & Layout",
    subcategory: "Controls",
    displayName: "Error Border",
    description: "Input error border",
  },
  "badge.background": {
    category: "UI & Layout",
    subcategory: "Controls",
    displayName: "Badge Background",
    description: "Badge background color",
  },
  "badge.foreground": {
    category: "UI & Layout",
    subcategory: "Controls",
    displayName: "Badge Text",
    description: "Text on badges",
  },
  "progressBar.background": {
    category: "UI & Layout",
    subcategory: "Controls",
    displayName: "Progress Bar",
    description: "Progress bar background",
  },
  "list.activeSelectionBackground": {
    category: "UI & Layout",
    subcategory: "Controls",
    displayName: "Active List BG",
    description: "Active list item background",
  },
  "list.activeSelectionForeground": {
    category: "UI & Layout",
    subcategory: "Controls",
    displayName: "Active List Text",
    description: "Active list item text",
  },
  "list.inactiveSelectionBackground": {
    category: "UI & Layout",
    subcategory: "Controls",
    displayName: "Inactive List BG",
    description: "Inactive-selected item background",
  },
  "list.hoverBackground": {
    category: "UI & Layout",
    subcategory: "Controls",
    displayName: "List Hover BG",
    description: "List item hover background",
  },
  "list.hoverForeground": {
    category: "UI & Layout",
    subcategory: "Controls",
    displayName: "List Hover Text",
    description: "List item hover text",
  },
  "notification.background": {
    category: "UI & Layout",
    subcategory: "Controls",
    displayName: "Notification BG",
    description: "Notification background color",
  },
  "notification.foreground": {
    category: "UI & Layout",
    subcategory: "Controls",
    displayName: "Notification Text",
    description: "Notification text color",
  },
  "notification.border": {
    category: "UI & Layout",
    subcategory: "Controls",
    displayName: "Notification Border",
    description: "Notification border color",
  },
  "notificationsErrorIcon.foreground": {
    category: "UI & Layout",
    subcategory: "Controls",
    displayName: "Error Icon",
    description: "Error icon color",
  },
  "notificationsWarningIcon.foreground": {
    category: "UI & Layout",
    subcategory: "Controls",
    displayName: "Warning Icon",
    description: "Warning icon color",
  },
  "notificationsInfoIcon.foreground": {
    category: "UI & Layout",
    subcategory: "Controls",
    displayName: "Info Icon",
    description: "Information icon color",
  },
  "editor.minimap.background": {
    category: "UI & Layout",
    subcategory: "Layout",
    displayName: "Minimap Background",
    description: "Editor minimap background",
  },
  "editor.minimap.foreground": {
    category: "UI & Layout",
    subcategory: "Layout",
    displayName: "Minimap Foreground",
    description: "Minimap stroke color",
  },
  "editor.minimapSlider.background": {
    category: "UI & Layout",
    subcategory: "Layout",
    displayName: "Minimap Slider BG",
    description: "Minimap slider background",
  },
  "editor.minimapSlider.hoverBackground": {
    category: "UI & Layout",
    subcategory: "Layout",
    displayName: "Minimap Slider Hover",
    description: "Minimap slider hover background",
  },
  "editor.minimapSlider.activeBackground": {
    category: "UI & Layout",
    subcategory: "Layout",
    displayName: "Minimap Slider Active",
    description: "Minimap slider active background",
  },

  // --- Extras ---
  "gitDecoration.addedResourceForeground": {
    category: "Extras",
    subcategory: "SCM",
    displayName: "Git Added Color",
    description: "Git added decoration color",
  },
  "gitDecoration.modifiedResourceForeground": {
    category: "Extras",
    subcategory: "SCM",
    displayName: "Git Modified Color",
    description: "Git modified decoration color",
  },
  "gitDecoration.deletedResourceForeground": {
    category: "Extras",
    subcategory: "SCM",
    displayName: "Git Deleted Color",
    description: "Git deleted decoration color",
  },
  "gitDecoration.untrackedResourceForeground": {
    category: "Extras",
    subcategory: "SCM",
    displayName: "Git Untracked Color",
    description: "Git untracked decoration color",
  },
  "gitDecoration.ignoredResourceForeground": {
    category: "Extras",
    subcategory: "SCM",
    displayName: "Git Ignored Color",
    description: "Git ignored decoration color",
  },
  "gitDecoration.conflictingResourceForeground": {
    category: "Extras",
    subcategory: "SCM",
    displayName: "Git Conflict Color",
    description: "Git conflict decoration color",
  },
  "debugToolBar.background": {
    category: "Extras",
    subcategory: "Debug",
    displayName: "Debug Toolbar BG",
    description: "Debug toolbar background",
  },
  "debugToolBar.border": {
    category: "Extras",
    subcategory: "Debug",
    displayName: "Debug Toolbar Border",
    description: "Border around debug toolbar",
  },
  "debugIcon.breakpointForeground": {
    category: "Extras",
    subcategory: "Debug",
    displayName: "Breakpoint Icon",
    description: "Breakpoint icon color",
  },
  "debugIcon.breakpointDisabledForeground": {
    category: "Extras",
    subcategory: "Debug",
    displayName: "Disabled Breakpoint Icon",
    description: "Disabled breakpoint color",
  },
  "debugIcon.breakpointUnverifiedForeground": {
    category: "Extras",
    subcategory: "Debug",
    displayName: "Unverified Breakpoint",
    description: "Unverified breakpoint color",
  },
  "debugIcon.breakpointCurrentStackframeForeground": {
    category: "Extras",
    subcategory: "Debug",
    displayName: "Current Stackframe Icon",
    description: "Current stack frame color",
  },
  "debugIcon.breakpointStackframeForeground": {
    category: "Extras",
    subcategory: "Debug",
    displayName: "Stackframe Icon",
    description: "Stack frame icon color",
  },
  "testing.iconFailed": {
    category: "Extras",
    subcategory: "Testing",
    displayName: "Test Failed Icon",
    description: "Failed test icon color",
  },
  "testing.iconErrored": {
    category: "Extras",
    subcategory: "Testing",
    displayName: "Test Errored Icon",
    description: "Errored test icon color",
  },
  "testing.iconPassed": {
    category: "Extras",
    subcategory: "Testing",
    displayName: "Test Passed Icon",
    description: "Passed test icon color",
  },
  "testing.iconQueued": {
    category: "Extras",
    subcategory: "Testing",
    displayName: "Test Queued Icon",
    description: "Queued test icon color",
  },
  "testing.iconUnset": {
    category: "Extras",
    subcategory: "Testing",
    displayName: "Test Unset Icon",
    description: "Unset test icon color",
  },
  "testing.iconSkipped": {
    category: "Extras",
    subcategory: "Testing",
    displayName: "Test Skipped Icon",
    description: "Skipped test icon color",
  },
  "breadcrumb.foreground": {
    category: "Extras",
    subcategory: "Breadcrumb",
    displayName: "Breadcrumb Text",
    description: "Breadcrumb text color",
  },
  "breadcrumb.background": {
    category: "Extras",
    subcategory: "Breadcrumb",
    displayName: "Breadcrumb Background",
    description: "Background of breadcrumbs",
  },
  "breadcrumb.focusForeground": {
    category: "Extras",
    subcategory: "Breadcrumb",
    displayName: "Breadcrumb Focus Text",
    description: "Focused breadcrumb text",
  },
  "breadcrumb.activeSelectionForeground": {
    category: "Extras",
    subcategory: "Breadcrumb",
    displayName: "Breadcrumb Active Text",
    description: "Active breadcrumb text color",
  },
  "welcomePage.background": {
    category: "Extras",
    subcategory: "Welcome",
    displayName: "Welcome Page Background",
    description: "Background of welcome page",
  },
  "welcomePage.buttonBackground": {
    category: "Extras",
    subcategory: "Welcome",
    displayName: "Welcome Button BG",
    description: "Buttons on welcome page",
  },
  "welcomePage.buttonHoverBackground": {
    category: "Extras",
    subcategory: "Welcome",
    displayName: "Welcome Button Hover",
    description: "Button hover on welcome page",
  },
  "settings.headerForeground": {
    category: "Extras",
    subcategory: "Settings",
    displayName: "Settings Header Text",
    description: "Text of settings headers",
  },
  "settings.modifiedItemIndicator": {
    category: "Extras",
    subcategory: "Settings",
    displayName: "Settings Modified Indicator",
    description: "Indicator for modified setting",
  },
  "settings.dropdownBackground": {
    category: "Extras",
    subcategory: "Settings",
    displayName: "Settings Dropdown BG",
    description: "Dropdown background in settings",
  },
  "settings.dropdownBorder": {
    category: "Extras",
    subcategory: "Settings",
    displayName: "Settings Dropdown Border",
    description: "Dropdown border in settings",
  },
  "settings.dropdownForeground": {
    category: "Extras",
    subcategory: "Settings",
    displayName: "Settings Dropdown Text",
    description: "Dropdown text in settings",
  },
  "menu.background": {
    category: "Extras",
    subcategory: "Menus",
    displayName: "Menu Background",
    description: "Background color of menus",
  },
  "menu.foreground": {
    category: "Extras",
    subcategory: "Menus",
    displayName: "Menu Text",
    description: "Text color in menus",
  },
};
